config/routes.rb
Rails.application.routes.draw do
  get 'cart/index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :products
  resources :webhooks
  post  "checkout/creat", to: "checkout#create"
  match '/add_to_cart/:product_id', to: 'carts#add_to_cart', as: 'add_to_cart', via: [:get, :post]
  get '/cart', to: 'carts#show', as: 'cart'
  match '/remove_from_cart/:product_id', to: 'carts#remove_from_cart', as: 'remove_from_cart', via: [:delete, :get]
  root "products#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/credit_card.rb
# app/models/credit_card.rb
class CreditCard < ApplicationRecord
    belongs_to :user
   
  end
  

app/models/product.rb
class Product < ApplicationRecord
    mount_uploader :image, ImageUploader
    has_many :carts
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :carts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def add_to_cart
    product = Product.find(params[:product_id])
    current_user.carts.create(product: product)
    redirect_to root_path, notice: "Product added to cart successfully"
  end
  def show
    @cart_items = current_user.carts.includes(:product)
  end
  def remove_from_cart
    product = Product.find(params[:product_id])
    current_user.carts.find_by(product: product).destroy
    redirect_to cart_path, notice: "Product removed from cart successfully"
  end
  
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def create
    product = Product.find(params[:id])
    @session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [{
         price_data: {
          currency: 'usd',
          unit_amount: product.price*product.quant,
          product_data: {
            name: product.name,
            description: product.description,
            },},
            quantity: 1,}],
      success_url: "https://625b-2405-201-402e-d027-8c75-5b87-57d6-71cd.ngrok-free.app/", 
      cancel_url: "https://625b-2405-201-402e-d027-8c75-5b87-57d6-71cd.ngrok-free.app/",  
      mode: 'payment',
    )
   redirect_to @session['url'], allow_other_host: true

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    if params[:search].present?
      @products = Product.where("name ILIKE ?", "%#{params[:search]}%")
    else
      @products = Product.all
    end
  end
  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product
    else
      render 'new'
    end
  end

  def show
    @product = Product.find(params[:id])
  end
  
  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path, notice: 'Product was successfully destroyed.'
  end

  private

  def product_params
    params.require(:product).permit(:image,:description,:name,:price)
  end
end

app/controllers/webhooks_controller.rb
class WebhooksController < ApplicationController
    skip_before_action :verify_authenticity_token
  
    def create
      payload = request.body.read
      sig_header = request.env['HTTP_STRIPE_SIGNATURE']
      event = nil
  
      begin
        event = Stripe::Webhook.construct_event(
          payload, sig_header, Rails.application.credentials[:stripe][:webhook]
        )
      rescue JSON::ParserError => e
        status 400
        return
      rescue Stripe::SignatureVerificationError => e
        # Invalid signature
        puts "Signature error"
        p e
        return
      end
  
      # Handle the event
      case event.type
      when 'checkout.session.completed'
        session = event.data.object
        @product = Product.find_by(price: session.amount_total)
        @product.increment!(:sales_count)
      end
  
      render json: { message: 'success' }
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/stripe_helper.rb
module StripeHelper
end

app/helpers/webhooks_helper.rb
module WebhooksHelper
end

app/views/carts/show.html.erb
<div class="container my-4">
  <h2>Your Cart</h2>
  <% if @cart_items.any? %>
    <div class="row">
      <% @cart_items.each do |c| %>
        <div class="col-md-4 mb-3">
          <div class="card" style="max-width: 300px;">
            <%= image_tag c.product.image.url, size: "250x150", class: "card-img-top" if c.product.image.present? %>
            <div class="card-body">
              <h5 class="card-title">Name: <%= c.product.name %></h5>
              <p class="card-text">Description: <%= c.product.description %></p>
              <p class="card-text">Sales Count: <%= c.product.sales_count %></p>
              <p class="card-text">Price: <%= c.product.price * c.product.quant %></p>
              <p class="card-text">Quantity: <%= c.quantity %></p>
              <%= link_to "Remove from Cart", remove_from_cart_path(product_id: c.product.id), class: "btn btn-danger my-2", method: :delete %>
              <%= button_to "Buy now!", checkout_creat_url, params: {id: cart_url}, data: {turbo: false} %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <p>Your cart is empty.</p>
  <% end %>
</div>

app/views/checkout/create.js.erb
var strip= Stripe("<%= Rails.application.credentials[:stripe][:secret]%>");
 stripe.redirectToCheckout({
    sesison_Id: '<%= @session.id%>'
 }).then(function (result){
    console.log(result.error.message);
 });

app/views/home/index.html.erb
<%= link_to "Create a New Product", new_product_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flipkart</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://js.stripe.com/v3/"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
       <%= render 'shared/navbar' %>
    <%= yield %>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

  </body>
</html>

app/views/products/create.html.erb
<h1>Product#create</h1>
<p>Find me in app/views/product/create.html.erb</p>

app/views/products/destroy.html.erb
<h1>Product#destroy</h1>
<p>Find me in app/views/product/destroy.html.erb</p>

app/views/products/index.html.erb
<div class="container my-4">
  <div class="row">
    <% @products.each do |product| %>
      <div class="col-md-4 mb-3">
        <div class="card rounded-3 bg-dark" style="max-width: 300px;">
          <%= link_to product_path(product) do %>
            <%= image_tag product.image.url, size: "250x150", class: "card-img-top rounded-3" if product.image.present? %>
          <% end %>
          <div class="card-body custom-link">
            <h5 class="card-title">Name: <%= product.name %></h5>
            <p class="card-text">Description: <%= product.description %></p>
            <p class="card-text">Price: <%= product.price %></p>
            <p class="card-text">Rating: <%= product.rating %></p>
            <%= button_to "Add to Cart", add_to_cart_path(product_id: product.id), class: "btn btn-outline-info my-2" %>
            <%= button_to "Buy now!", checkout_creat_path, params: { id: product.id }, class: "btn btn-outline-success my-2", data: { turbo: false } %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<style>
  .custom-link {
    text-decoration: none;
    color: red;
  }
</style>

app/views/products/new.html.erb
<%= form_for @product, html: { multipart: true } do |f| %>
  <%= f.label :image %>
  <%= f.file_field :image %><br>

  <%= f.label :category %>
  <%= f.select :category, ['electronic', 'play', 'fashion', 'phone', 'laptop'] %><br>

  <%= f.submit "Create Product" %>
<% end %>

app/views/products/show.html.erb
<div class="container my-4">
  <div class="row">
    <div class="col-md-4 mb-3">
      <div class="card" style="max-width: 300px;">
        <%= image_tag @product.image.url, size: "250x150", class: "card-img-top" if @product.image.present? %>
        <div class="card-body">
          <h5 class="card-title">Name: <%= @product.name %></h5>
          <p class="card-text">Description: <%= @product.description %></p>
          <p class="card-text">Price: <%= @product.price %></p>
          <p class="card-text">Rating: <%= @product.rating %></p>
          <p class="card-text">Sales Count: <%= @product.sales_count %></p>
          <%= button_to "Add to Cart", add_to_cart_path(@product.id), class: "btn btn-outline-info my-2" %>
          <%= button_to "Buy now!", checkout_creat_path, params: { id: @product.id }, class: "btn btn-outline-success my-2", data: { turbo: false } %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/update.html.erb
<h1>Product#update</h1>
<p>Find me in app/views/product/update.html.erb</p>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="<%= root_path %>">Flipkart</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse mx-5" id="navbarSupportedContent">
        <%= form_tag(products_path, method: :get) do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search" %>
        <%= submit_tag "Search", class: "btn btn-outline-primary " %>
    <% end %>
  </div>
    <% if user_signed_in? %>
      <h5 style="color:green"><%= current_user.email %></h5>
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link btn btn-outline-info rounded-5 mx-2' %>
      <%= button_to 'Logout', destroy_user_session_path, method: :delete, class: 'navbar-link btn btn-outline-danger rounded-0', data: { turbo_frame: 'navbar', turbo_method: :delete } %>
    <% else %>
      <%= link_to 'Sign up', new_user_registration_path, :class => 'navbar-link btn btn-outline-success rounded-0' %>
      <%= link_to 'Login', new_user_session_path, :class => 'navbar-link btn btn-success rounded-0' %>
    <% end %>
      <%= link_to "Cart", cart_path, class: "btn btn-outline-primary rounded-5 mx-5" %>

</nav>